### ISSUE TITLE
CGT Math not displayed...

### ISSUE THREAD

**Issue by mvukov** [acado/acado.github.io#1]
... it looks like MathJax problem. See https://github.com/acado/acado/issues/120

**Comment by mvukov** [comment]
... seems to work again but I will monitor this for a while...

**Comment by erihe251** [comment]
Tried it just now and for me the problem persists.  (Yes, I cleared my browser cache :))

**Comment by mvukov** [comment]
dunno... on my osx machine it works in both chrome and safari... on chrome i had to do one `ctrl+r` though...

**Comment by erihe251** [comment]
Ok, it's pretty strange, I've tried a couple of times during the day. Once I got it working in Chrome and once in FF, but in FF all formulas rendered as white. The other times I've just been getting the math-code. I'm on OSX, also tried FF on CentOS.

**Comment by rienq** [comment]
Indeed strange, it is not working here either.. not in Chrome, nor in FF

**Comment by mvukov** [comment]
To me it seems that from time to time MathJax does not work on their own servers. I don't have any idea about how to fix this but to install MathJax on GitHub -- if ever possible. Who want's to fix this should re-open the issue.
